name: native-jfr-demo
on:
  push:
    paths:
      - 'native-jfr-demo/**'
      - '.github/workflows/native-jfr-demo.yml'
  pull_request:
    paths:
      - 'native-jfr-demo/**'
      - '.github/workflows/native-jfr-demo.yml'
  schedule:
    - cron: "0 0 1 * *" # run every month
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: write # for `native-image-pr-reports` option
jobs:
  run:
    name: Run 'native-jfr-demo'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'dev'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          native-image-pr-reports: 'true'
      - name: Run 'native-jfr-demo'
        run: 
          gu install visualvm
          cd native-jfr-demo
          javac JFRDemo.java
          native-image --enable-monitoring=jfr JFRDemo
          ./jfrdemo -XX:+FlightRecorder -XX:StartFlightRecording="filename=recording.jfr"
          jfr print recording.jfr
