name: tiny-java-containers
on:
  push:
    paths:
      - 'tiny-java-containers/**'
      - '.github/workflows/tiny-java-containers.yml'
  schedule:
    - cron: "0 0 1 * *" # run every month
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    name: Run 'tiny-java-containers'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest' # EE dev builds not supported
          gds-token: ${{ secrets.GDS_TOKEN }}
          java-version: '19'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run 'tiny-java-containers'
        run: |
          cd tiny-java-containers
          sleep_period=10
          #
          # Setup musl toolchain
          #
          ./setup-musl.sh
          #
          # Hello World
          #
          cd helloworld
          ./build.sh
          ./hello
          ./hello.upx
          docker run --rm hello:upx
          cd ..
          #
          # jwebserver
          #
          cd jwebserver
          #
          # Dynamic
          #
          # ./build-dynamic.sh
          # docker images
          # #container_id=$(docker run -d --rm -p8001:8000 jwebserver:distroless-java-base.dynamic)
          # docker run -d --rm -p8001:8000 jwebserver:distroless-java-base.dynamic &
          # docker ps 
          # container_id=$(docker ps -q)
          # docker logs -f $container_id
          # sleep $sleep_period
          # docker ps 
          # docker logs $container_id
          # curl "http://localhost:8001"
          # docker stop $container_id
          #
          # Mostly Static
          #
          ./build-mostly.sh
          container_id=$(docker run -d --rm -p8002:8000 jwebserver:distroless-base.mostly)
          sleep $sleep_period
          curl "http://localhost:8002"
          docker stop $container_id          
          #
          # Static Scratch
          #
          ./build-static.sh
          container_id=$(docker run -d --rm -p8003:8000 jwebserver:scratch.static)
          sleep $sleep_period
          curl "http://localhost:8003"
          docker stop $container_id
          #
          # Static Scratch UPX
          #
          container_id=$(docker run -d --rm -p8004:8000 jwebserver:scratch.static-upx)
          sleep $sleep_period
          curl "http://localhost:8004"
          docker stop $container_id
          #
          # Distroless Static
          #
          container_id=$(docker run -d --rm -p8005:8000 jwebserver:distroless-static.static)
          sleep $sleep_period
          curl "http://localhost:8005"
          docker stop $container_id
          #
          # Alping Static
          #
          container_id=$(docker run -d --rm -p8006:8000 jwebserver:alpine.static)
          sleep $sleep_period
          curl "http://localhost:8006"
          docker stop $container_id
          #
          # jlink
          # 
          ./build-jlink.sh
          container_id=$(docker run -d --rm -p8007:8000 jwebserver:distroless-java-base.jlink)
          sleep $sleep_period
          curl "http://localhost:8007"
          docker stop $container_id
